### ISSUE TITLE
Why do you need to run the docker image with "--privileged"

### ISSUE THREAD

**Issue by EricAtORS** [oposs/tl-docker#2]
Hi,

Why do you need to run the docker container with `--privileged`? Can the reason be in the readme.md?

Thanks for this. It's going to be really helpful.

**Comment by EricAtORS** [comment]
Running as privileged is not needed. It is only needed to start and manage systemd.

**Comment by oetiker** [comment]
Hi Eric

Actually the thinlinc daemons also need some privileged access, but as shown in the README you can give those capabilities exp-licitly if you want. One might also think about 'fixing' thinlinc to not require these privileges. I have not investigated this option more closely.

**Comment by EricAtORS** [comment]
Thanks for the reply @oetiker 

I needed to investigate it closer because I was trying to use it with a different base image for which systemd was not running. 

```
mkdir /run/sshd -p
/usr/sbin/sshd
/bin/bash --login -c /opt/thinlinc/sbin/tlwebadm
```

Running those commands was sufficient to bring up ThinLinc and the ssh server.
