### ISSUE TITLE
Is it possible to run it on cloud shells?

### ISSUE THREAD

**Issue by idevcde** [oposs/tl-docker#3]
Hi, Thank you for this docker.  I am wondering if it is possible to run it on cloud shells. It seems that I am getting stuck at "Finished Update UTMP about System Runlevel Changes" in both above mentioned cases. Would you have any comment / advice please?

**Comment by oetiker** [comment]
Hi @idevcde 

I have not either ... what is your usage scenario?

cheers
tobi

**Comment by idevcde** [comment]
Hi tobi, thanks for the reply. Frankly, those are the places where I have docker immediately available and I wanted to test tl-docker there. In general sometimes GUI access would be useful. I have access to several machines without GUI, however, I am able to upload a docker there without almost any restrictions. So in general, I was doing testing and I was wondering if it could be run as a docker and some kind of a streaming platform or maybe even with the use of Cloudflared Secure Tunnel (https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/run-tunnel/trycloudflare#use-trycloudflare) in cases where there is no public ip available.

**Comment by oetiker** [comment]
could it be that all is working? note that you have to interactively finish setting up the docker as described in the README

**Comment by oetiker** [comment]
note also, that with tl-docker you will end up in an 'enclosed' environment 'inside' the docker, with no access to the environment where the docker is running.

**Comment by idevcde** [comment]
Thank you for the reply. The 'enclosed' environment 'inside' the docker is fine for me. I can not exclude that all is running fine. I do not have advanced knowledge in this field. However, I did some additional testing. 

```
# When:
docker run --privileged --pull=always --name my-tl-demo --publish 9922:22 -t oposs/tl-ubuntu

# I am receiving:
[FAILED] Failed to start Load Kernel Modules.
See 'systemctl status systemd-modules-load.service' for details.
[FAILED] Failed to start Load AppArmor profiles.
See 'systemctl status apparmor.service' for details.

# Despite it I proceeded further and in another cloud shell terminal I installed cloudflared (its Debian there):
echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/ buster main' |
sudo tee /etc/apt/sources.list.d/cloudflare-main.list
sudo curl https://pkg.cloudflare.com/cloudflare-main.gpg -o /usr/share/keyrings/cloudflare-main.gpg
sudo apt-get update
sudo apt-get install cloudflared

# And then I created a tunnel in the following way:
cloudflared tunnel --url ssh://127.0.0.1:9922

# In the other shell terminal I added user and pointed to 127.0.0.1:
docker exec my-tl-demo tlcfg add-user myuser mypassword
docker exec my-tl-demo tlcfg set-hostname 127.0.0.1

# In ThinLinc client on my local machine I changed the ssh port to 9922, entered myuser and mypassword credentials and
# pointed to a tunnel name as provided by cloudflared (without https).
```

Despite it and some other tries I am always receiving "Connection to server "..." timed out. Check your settings." As for now, my main concern are docker FAILED messages and even more all the addresses and ports for cloudflared. I guess all this is a little bit hacky, however, should you have any comments or advice please let me know. I will also give it another try on a machine that I was hoping to run it in a more permanent way soon. Thank you once again for tl-docker.

**Comment by idevcde** [comment]
Hi, as for now, I do not think its possible to run this docker on cloud due to [FAILED] messages so I think that I would have to install docker software on one of the computers in order to correctly test it. Having the opportunity, can I have one more question? 

Do you think that it might be possible to run:
- [jupyter/datascience-notebook docker](https://hub.docker.com/r/jupyter/datascience-notebook) together with 
- [tl-docker](https://github.com/oposs/tl-docker) and with 
- [cloudflared docker](https://hub.docker.com/r/cloudflare/cloudflared)?

The way I am able to deploy docker is by:
- pulling my own image from a container registry (can be public),
- providing additional command that must be Jupyter compatible and that currently defaults to: `jupyter notebook --allow-root --ip=0.0.0.0 --no-browser --NotebookApp.trust_xheaders=True --NotebookApp.disable_check_xsrf=False --NotebookApp.allow_remote_access=True --NotebookApp.allow_origin='*'` if left blank 
and by
- providing container user = optional user; defaults to 'root' if left blank.

What I was thinking about is the `data science jupyter lab` and at the same time access to GUI desktop by `cloudflared tunnel `(cause there is no public ip). I think that due to some reasons, it would significantly help with my workflow. I have rather basic knowledge about docker thus I am wondering if this might be possible at all? Does it make sense to try to build such a docker by a beginner or would it be rather very complicated?

**Comment by oetiker** [comment]
@idevcde I am not sure I am properly understanding what you try to achive ... the tl-docker essentially is a way of running a ubuntu workstation inside a docker container and access it with the thinlinc client ... 

Jupiter has its own webinterface, I don't see a use case where it integrates with thinlinc ...

As for using a cloudflare tunnel, thinlinc uses standard ssh for communication, so I guess this should be no problem.

**Comment by idevcde** [comment]
Hi, @oetiker !
**1.** I was able to ssh to the tl-docker, however, I was not able to connect with TL.

BTW, I think there is a small typo in your documentation ([](https://github.com/oposs/tl-docker#configuration)).

There is:
`docker exec my-demo-docker tlcfg add-ssh-user myuser "public ssh key"`

I think it should be:
`docker exec **my-tl-demo** tlcfg add-ssh-user myuser "public ssh key"`

Also I do not why, but when using ssh key like:

`ssh -i "(absolute path to) public ssh key" myuser@remotehost -p 9922`

after initial ssh login, next I am asked for the password. So in order to proceed further I have to add the same user again but this time not with ssh key but with a password: `docker exec my-tl-demo tlcfg add-user myuser mypassword`. Than I am able to get this ssh access.

Taking it into account and assuming (its nothing more than a guess) that even though those "`[FAILED] Failed to start Load Kernel Modules`." and "`[FAILED] Failed to start Load AppArmor profiles.`" messages, ThinkLinc server is somehow working, the need to provide password apart to ssh key may be preventing ThinLinc Client to access the docker. I don't know - of course all this can be due to [FAILED] messages. GCS is a specific environment.

**2.** Additional info:
>I am not sure I am properly understanding what you try to achive ... the tl-docker essentially is a way of running a ubuntu workstation inside a docker container and access it with the thinlinc client ... Jupiter has its own webinterface, I don't see a use case where it integrates with thinlinc ...

Right, I am not an expert in this area, so I might not be ultra precise, however, I will try to provide additional info. What I was thinking about is the extension of a functionality of my setup that currently consists of `jupyter/datascience-notebook` docker. You are right, this Jupyter environment starts with a web interface. I am accessing it in a web browser. However, it is not running on my local machine but it is deployed on a cluster. What I was thinking about was to have full GUI accessed by ThinkLinc client apart to this Jupyter web interface. So when I am working in Jupyter in a web browser, I can have another window where I can operate in Ubuntu GUI environment with the use of ThinkLinc. Thus I was hoping to test tl-docker and maybe extend it by adding jupyter/datascience-notebook or the other way around. In general I wanted to deploy custom docker on this cluster (other than default dockers available on this cluster) . On the way I learned that in order to do it I probably need to have jupyter/datascience-notebook docker as a base. So do not know if this is possible at all.

In addition, I just logged into this fresh jupyter/datascience-notebook environment deployed on a cluster. Its running on Ubuntu. I unminimized it, installed ubuntu-desktop-minimal, setted openssh-server and cloudflared and another user. I was able to ssh to it, however, when I tried to install tl-server or start GUI services I received info as below. Its a bit pity because on this cluster I got access to NVIDIA and I like ThinLinc as much as Nice DCV (that also does not want to work) but I am running out of ideas so I think I will take a break. :-)

tl-server 
```

Configuring Services
====================

Configuring and starting ThinLinc services... failed.

An error occurred whilst trying to configure and start one or more of
ThinLinc's services. You will need to manually install and start each
of the ThinLinc services vsmserver, vsmagent, tlwebaccess and
tlwebadm. It is not possible to use ThinLinc until this problem is
solved.
```

I also tried to start GUI and I received:

```
(base) sudo systemctl isolate graphical
System has not been booted with systemd as init system (PID 1). Can't operate.
```

And when trying to startx:

```
(base) startx
xauth:  file /home/jovyan/.Xauthority does not exist
X.Org X Server 1.20.13
X Protocol Version 11, Revision 0
Build Operating System: linux Ubuntu
Current Operating System: Linux njs4zf1u3e 5.4.0-65-generic #73~18.04.1-Ubuntu SMP Tue Jan 19 09:02:24 UTC 2021 x86_64
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-5.4.0-65-generic root=/dev/mapper/ubuntu--vg-root ro quiet splash scsi_mod.use_blk_mq=Y vt.handoff=1
Build Date: 14 December 2021  02:14:13PM
xorg-server 2:1.20.13-1ubuntu1~20.04.2 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.38.4
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Wed Jan  5 20:30:43 2022
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) parse_vt_settings: Cannot open /dev/tty0 (No such file or directory)
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
xinit: giving up
xinit: unable to connect to X server: Cannot assign requested address
xinit: server error
```

**Comment by idevcde** [comment]
Hi, can I ask you two short questions?

1. Is it possible to have a user with sudo inside tl-docker?

2. Is it possible to connect with TL Client with ProxyCommand? 

As I understand it in order to access a machine by cloudflared generated url, I have to use such a config as below and cloudflared-windows-amd64 software.
```
Host *.trycloudflare.com
	HostName %h
	User root
	Port 22
	ProxyCommand C:\cloudflared\cloudflared-windows-amd64 access ssh --hostname %h
```

**Comment by oetiker** [comment]
> Hi, can I ask you two short questions?
> 
>     1. Is it possible to have a user with sudo inside tl-docker?

Sure, it is a normal Linux environment ... 

>     2. Is it possible to connect with TL Client with ProxyCommand?

Sure, as long as ssh can connect it will work. Note that custom ssh configs go into `~/.thinlinc/config`

**Comment by oetiker** [comment]
> Right, I am not an expert in this area, so I might not be ultra precise, however, I will try to provide additional info. What I was thinking about is the extension of a functionality of my setup that currently consists of `jupyter/datascience-notebook` docker. You are right, this Jupyter environment starts with a web interface. I am accessing it in a web browser. However, it is not running on my local machine but it is deployed on a cluster. What I was thinking about was to have full GUI accessed by ThinkLinc client apart to this Jupyter web interface. So when I am working in Jupyter in a web browser, I can have another window where I can operate in Ubuntu GUI environment with the use of ThinkLinc. Thus I was hoping to test tl-docker and maybe extend it by adding jupyter/datascience-notebook or the other way around. In general I wanted to deploy custom docker on this cluster (other than default dockers available on this cluster) . On the way I learned that in order to do it I probably need to have jupyter/datascience-notebook docker as a base. So do not know if this is possible at all.

yes, that should work well

thanks for the hint with the readme ... fixed

**Comment by idevcde** [comment]
You are welcome tobi and thanks.
